<?php
?>
<ol>
    <li><strong>LGHATRMOI</strong></li>
    <li><strong>ARRAY</strong></li>
    <li><strong>TCLRHWAFO</strong></li>
    <li><strong>NUTPI</strong></li>
    <li><strong>UTUTOP</strong></li>
    <li><strong>SPOSCER</strong></li>
    <li><strong>OEDSCOPEUD</strong></li>
    <li><strong>TETMTSEAN</strong></li>
    <li><strong>LARABVEI</strong></li>
</ol>
<p>Answer Key</p>
<ol>
    <li><strong>LGHATRMOI&nbsp;=&nbsp;ALGORITHM</strong></li>
    <li><strong>ARRAY&nbsp;=&nbsp;ARRAY</strong></li>
    <li><strong>TCLRHWAFO&nbsp;=&nbsp;FLOWCHART</strong></li>
    <li><strong>NUTPI&nbsp;=&nbsp;INPUT</strong></li>
    <li><strong>UTUTOP&nbsp;=&nbsp;OUTPUT</strong></li>
    <li><strong>SPOSCER&nbsp;=&nbsp;PROCESS</strong></li>
    <li><strong>OEDSCOPEUD&nbsp;=&nbsp;PSEUDOCODE</strong></li>
    <li><strong>TETMTSEAN&nbsp;=&nbsp;STATEMENT</strong></li>
    <li><strong>LARABVEI&nbsp;=&nbsp;VARIABLE</strong></li>
</ol>